# Generated by Django 4.2.16 on 2025-01-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MojeFinanse', '0002_expenses_delete_exepnses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='desc',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
