# Generated by Django 4.2.16 on 2025-01-28 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MojeFinanse', '0005_paymentmethod_expenses_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='payment_method',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MojeFinanse.paymentmethod'),
        ),
    ]
