# Generated by Django 4.2.16 on 2025-01-28 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MojeFinanse', '0006_alter_expenses_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MojeFinanse.category'),
        ),
    ]
